export const businessTemplates = [
  {
    slug: "non-disclosure-agreement",
    titleEn: "Non-Disclosure Agreement (Mutual / Unilateral)",
    titleNp: "गोपनीयता सम्झौता (पारस्परिक / एकतर्फी)",
    descriptionEn: "Protects confidential information shared between two parties.",
    descriptionNp: "दुई पक्षबीच आदानप्रदान हुने गोप्य जानकारीको सुरक्षा गर्ने सम्झौता।",
    requiresLawyerReview: true,
    isGovernmentFormat: false,
    systemPromptEn:
      "Draft a Non-Disclosure Agreement under Nepali contract practice. Use only the party " +
      "details, disclosure direction (mutual or unilateral), purpose, and term provided. " +
      "Structure: definition of confidential information, obligations of receiving party, " +
      "exclusions (already public, independently developed, required by law), term of " +
      "confidentiality, remedies, governing law, signature block. End with the standard draft " +
      "disclaimer.",
    systemPromptNp:
      "नेपाली सम्झौता अभ्यास अनुसार गोपनीयता सम्झौता मस्यौदा गर्नुहोस्। प्रयोगकर्ताले दिएका पक्षको " +
      "विवरण, प्रकटीकरणको दिशा (पारस्परिक/एकतर्फी), उद्देश्य र अवधि मात्र प्रयोग गर्नुहोस्। " +
      "अन्त्यमा मानक ड्राफ्ट अस्वीकरण राख्नुहोस्।",
    fields: [
      {
        key: "disclosureType",
        type: "SELECT",
        label: { en: "Disclosure type", np: "प्रकटीकरणको प्रकार" },
        required: true,
        step: 0,
        sortOrder: 0,
        options: [
          { value: "mutual", label: { en: "Mutual (both parties share)", np: "पारस्परिक" } },
          { value: "unilateral", label: { en: "Unilateral (one party discloses)", np: "एकतर्फी" } },
        ],
      },
      {
        key: "firstParty",
        type: "PARTY_BLOCK",
        partyRole: "first_party",
        includeCitizenshipNumber: true,
        includeCompanyRegistration: true,
        label: { en: "First Party", np: "पहिलो पक्ष" },
        required: true,
        step: 0,
        sortOrder: 1,
      },
      {
        key: "secondParty",
        type: "PARTY_BLOCK",
        partyRole: "second_party",
        includeCitizenshipNumber: true,
        includeCompanyRegistration: true,
        label: { en: "Second Party", np: "दोस्रो पक्ष" },
        required: true,
        step: 0,
        sortOrder: 2,
      },
      {
        key: "purpose",
        type: "TEXTAREA",
        label: { en: "Purpose of disclosure", np: "प्रकटीकरणको उद्देश्य" },
        required: true,
        step: 1,
        sortOrder: 0,
        maxLength: 800,
      },
      {
        key: "confidentialityTermYears",
        type: "NUMBER",
        label: { en: "Confidentiality term (years)", np: "गोपनीयता अवधि (वर्ष)" },
        required: true,
        step: 1,
        sortOrder: 1,
        min: 1,
        max: 20,
      },
      {
        key: "customClause",
        type: "FREE_TEXT_CLAUSE",
        label: { en: "Describe any additional clause (optional)", np: "थप धारा वर्णन गर्नुहोस् (वैकल्पिक)" },
        required: false,
        step: 2,
        sortOrder: 0,
        maxLength: 1500,
      },
    ],
    clauses: [
      {
        key: "definition",
        titleEn: "Definition of Confidential Information",
        titleNp: "गोप्य जानकारीको परिभाषा",
        bodyEn: "\"Confidential Information\" means all non-public information disclosed by either party in connection with {{purpose}}.",
        bodyNp: "\"गोप्य जानकारी\" भन्नाले {{purpose}} सम्बन्धमा कुनै पनि पक्षले प्रकट गरेको सार्वजनिक नभएको जानकारी सम्झनुपर्छ।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 0,
      },
      {
        key: "obligations",
        titleEn: "Obligations of Receiving Party",
        titleNp: "प्राप्तकर्ता पक्षको दायित्व",
        bodyEn: "The receiving party shall use Confidential Information solely for the stated purpose and shall not disclose it to third parties without prior written consent.",
        bodyNp: "प्राप्तकर्ता पक्षले गोप्य जानकारी उल्लिखित उद्देश्यका लागि मात्र प्रयोग गर्नेछ र पूर्व लिखित सहमति बिना तेस्रो पक्षलाई प्रकट गर्ने छैन।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 1,
      },
      {
        key: "exclusions",
        titleEn: "Exclusions",
        titleNp: "अपवादहरू",
        bodyEn: "Obligations do not apply to information that is already public, independently developed, or required to be disclosed by law.",
        bodyNp: "पहिले नै सार्वजनिक भइसकेको, स्वतन्त्र रूपमा विकसित गरिएको, वा कानुनले प्रकट गर्न आवश्यक ठहराएको जानकारीमा दायित्व लागू हुँदैन।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 2,
      },
      {
        key: "term",
        titleEn: "Term",
        titleNp: "अवधि",
        bodyEn: "This Agreement's confidentiality obligations remain in effect for {{confidentialityTermYears}} years from the date of signing.",
        bodyNp: "यस सम्झौताको गोपनीयता दायित्व हस्ताक्षर मितिदेखि {{confidentialityTermYears}} वर्षसम्म कायम रहनेछ।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 3,
      },
      {
        key: "dispute_resolution",
        titleEn: "Governing Law & Dispute Resolution",
        titleNp: "लागू कानुन र विवाद समाधान",
        bodyEn: "This Agreement is governed by the laws of Nepal; disputes shall be subject to the jurisdiction of the competent courts of Nepal.",
        bodyNp: "यो सम्झौता नेपालको कानुनद्वारा शासित हुनेछ; विवाद नेपालको सक्षम अदालतको क्षेत्राधिकार अन्तर्गत रहनेछ।",
        isDefault: true,
        isToggleable: true,
        sortOrder: 4,
        riskFlagIfMissing: "No governing law / dispute resolution clause selected.",
      },
    ],
  },
  {
    slug: "memorandum-of-understanding",
    titleEn: "Memorandum of Understanding (MOU)",
    titleNp: "समझदारी पत्र",
    descriptionEn: "A non-binding statement of intent between two or more parties to collaborate.",
    descriptionNp: "दुई वा बढी पक्षबीच सहकार्यको आशयको गैर-बाध्यकारी कथन।",
    requiresLawyerReview: true,
    isGovernmentFormat: false,
    systemPromptEn:
      "Draft a Memorandum of Understanding reflecting the parties, shared objective, respective " +
      "responsibilities, and duration provided by the user. Clearly state whether it is binding " +
      "or non-binding as specified. Do not fabricate obligations beyond what was described. End " +
      "with the standard draft disclaimer.",
    systemPromptNp:
      "प्रयोगकर्ताले दिएका पक्ष, साझा उद्देश्य, जिम्मेवारी र अवधिको आधारमा समझदारी पत्र मस्यौदा गर्नुहोस्। " +
      "यो बाध्यकारी हो वा होइन स्पष्ट उल्लेख गर्नुहोस्। अन्त्यमा मानक ड्राफ्ट अस्वीकरण राख्नुहोस्।",
    fields: [
      {
        key: "firstParty",
        type: "PARTY_BLOCK",
        partyRole: "first_party",
        includeCompanyRegistration: true,
        includeCitizenshipNumber: false,
        label: { en: "First Party", np: "पहिलो पक्ष" },
        required: true,
        step: 0,
        sortOrder: 0,
      },
      {
        key: "secondParty",
        type: "PARTY_BLOCK",
        partyRole: "second_party",
        includeCompanyRegistration: true,
        includeCitizenshipNumber: false,
        label: { en: "Second Party", np: "दोस्रो पक्ष" },
        required: true,
        step: 0,
        sortOrder: 1,
      },
      {
        key: "objective",
        type: "TEXTAREA",
        label: { en: "Shared objective", np: "साझा उद्देश्य" },
        required: true,
        step: 1,
        sortOrder: 0,
        maxLength: 1000,
      },
      {
        key: "isBinding",
        type: "CHECKBOX",
        label: { en: "This MOU is legally binding", np: "यो समझदारी पत्र कानुनी रूपमा बाध्यकारी छ" },
        required: false,
        step: 1,
        sortOrder: 1,
        defaultChecked: false,
      },
      {
        key: "durationMonths",
        type: "NUMBER",
        label: { en: "Duration (months)", np: "अवधि (महिना)" },
        required: true,
        step: 1,
        sortOrder: 2,
        min: 1,
        max: 120,
      },
      {
        key: "customClause",
        type: "FREE_TEXT_CLAUSE",
        label: { en: "Describe any additional clause (optional)", np: "थप धारा वर्णन गर्नुहोस् (वैकल्पिक)" },
        required: false,
        step: 2,
        sortOrder: 0,
        maxLength: 1500,
      },
    ],
    clauses: [
      {
        key: "purpose",
        titleEn: "Purpose",
        titleNp: "उद्देश्य",
        bodyEn: "The parties intend to collaborate on: {{objective}}.",
        bodyNp: "पक्षहरूले निम्न विषयमा सहकार्य गर्ने आशय राख्दछन्: {{objective}}।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 0,
      },
      {
        key: "binding_status",
        titleEn: "Binding Status",
        titleNp: "बाध्यकारी अवस्था",
        bodyEn: "This MOU {{isBinding}} constitutes a legally binding agreement between the parties.",
        bodyNp: "यो समझदारी पत्र पक्षहरूबीच {{isBinding}} कानुनी रूपमा बाध्यकारी सम्झौता हो।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 1,
        riskFlagIfMissing: "Binding status is unclear — state explicitly whether this MOU is binding.",
      },
      {
        key: "duration",
        titleEn: "Duration",
        titleNp: "अवधि",
        bodyEn: "This MOU remains in effect for {{durationMonths}} months from the date of signing, unless extended by mutual written consent.",
        bodyNp: "यो समझदारी पत्र हस्ताक्षर मितिदेखि {{durationMonths}} महिनासम्म कायम रहनेछ, जबसम्म आपसी लिखित सहमतिले नबढाइएको हुन्छ।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 2,
      },
    ],
  },
] as const;
