export const categorySeeds = [
  {
    slug: "employment",
    nameEn: "Employment",
    nameNp: "रोजगारी",
    descriptionEn: "Offer letters, contracts, termination, and other employment documents.",
    descriptionNp: "प्रस्ताव पत्र, सम्झौता, अवकाश लगायतका रोजगारी सम्बन्धी कागजातहरू।",
    icon: "briefcase",
    sortOrder: 1,
  },
  {
    slug: "rental-property",
    nameEn: "Rental & Property",
    nameNp: "भाडा तथा सम्पत्ति",
    descriptionEn: "Residential, commercial, and land rental or lease agreements.",
    descriptionNp: "घर, पसल, कार्यालय तथा जग्गा भाडा वा लिज सम्झौता।",
    icon: "home",
    sortOrder: 2,
  },
  {
    slug: "business-commercial",
    nameEn: "Business & Commercial",
    nameNp: "व्यापार तथा वाणिज्य",
    descriptionEn: "NDAs, partnership agreements, MOUs, and other commercial contracts.",
    descriptionNp: "गोपनीयता सम्झौता, साझेदारी सम्झौता, समझदारी पत्र लगायत।",
    icon: "briefcase-business",
    sortOrder: 3,
  },
  {
    slug: "personal-family",
    nameEn: "Personal & Family",
    nameNp: "व्यक्तिगत तथा पारिवारिक",
    descriptionEn: "Power of attorney, affidavits, gift deeds, and personal loan notes.",
    descriptionNp: "मुख्तियारनामा, स्वघोषणा पत्र, दान पत्र तथा ऋण सम्झौता।",
    icon: "users",
    sortOrder: 4,
  },
  {
    slug: "consumer-general",
    nameEn: "Consumer & General",
    nameNp: "उपभोक्ता तथा सामान्य",
    descriptionEn: "Purchase/sale agreements, legal notices, and undertaking letters.",
    descriptionNp: "खरिद-बिक्री सम्झौता, कानूनी सूचना तथा कबुलियतनामा।",
    icon: "shopping-cart",
    sortOrder: 5,
  },
  {
    slug: "startup-digital",
    nameEn: "Startup / Digital",
    nameNp: "स्टार्टअप / डिजिटल",
    descriptionEn: "Founders' agreements, terms of service, privacy policy, and IP assignment.",
    descriptionNp: "संस्थापक सम्झौता, सेवाका सर्तहरू, गोपनीयता नीति तथा बौद्धिक सम्पत्ति हस्तान्तरण।",
    icon: "rocket",
    sortOrder: 6,
  },
] as const;
