// Seed data for the Employment category.
// Field/clause shapes follow src/types/template-engine.ts — kept as plain
// objects here (rather than imported zod types) so `tsx prisma/seed.ts` has
// no dependency on the Next.js path-alias resolver.

export const employmentTemplates = [
  {
    slug: "employment-offer-letter",
    titleEn: "Employment Offer Letter",
    titleNp: "रोजगारी प्रस्ताव पत्र",
    descriptionEn: "A formal offer of employment stating role, compensation, and start date.",
    descriptionNp: "पद, पारिश्रमिक र सुरु मितिसहितको औपचारिक रोजगारी प्रस्ताव पत्र।",
    requiresLawyerReview: true,
    isGovernmentFormat: false,
    systemPromptEn:
      "You are drafting a formal Employment Offer Letter under Nepali employment practice. " +
      "Use the exact party names, job title, compensation, and dates provided — never invent " +
      "facts. Structure: letterhead block, date, addressee, opening offer paragraph, position " +
      "and reporting line, compensation and benefits, start date, employment type/probation " +
      "terms if applicable, at-will/termination basis, confidentiality (if included), " +
      "non-compete (if included), acceptance signature block. Use formal English register. " +
      "End with the standard draft disclaimer.",
    systemPromptNp:
      "तपाईं नेपाली रोजगारी अभ्यास अनुसार औपचारिक रोजगारी प्रस्ताव पत्र मस्यौदा गर्दै हुनुहुन्छ। " +
      "प्रयोगकर्ताले दिएका पक्षका नाम, पद, पारिश्रमिक र मितिहरू मात्र प्रयोग गर्नुहोस् — नयाँ तथ्य नबनाउनुहोस्। " +
      "औपचारिक कानूनी नेपाली भाषा प्रयोग गर्नुहोस् (जस्तै: नियुक्ति, पारिश्रमिक, सर्तहरू)। " +
      "अन्त्यमा मानक ड्राफ्ट अस्वीकरण राख्नुहोस्।",
    fields: [
      {
        key: "employer",
        type: "PARTY_BLOCK",
        partyRole: "employer",
        includeCompanyRegistration: true,
        includeCitizenshipNumber: false,
        label: { en: "Employer", np: "रोजगारदाता" },
        required: true,
        step: 0,
        sortOrder: 0,
      },
      {
        key: "employee",
        type: "PARTY_BLOCK",
        partyRole: "employee",
        includeCitizenshipNumber: true,
        includeCompanyRegistration: false,
        label: { en: "Employee", np: "कर्मचारी" },
        required: true,
        step: 0,
        sortOrder: 1,
      },
      {
        key: "jobTitle",
        type: "TEXT",
        label: { en: "Job title", np: "पद" },
        required: true,
        step: 1,
        sortOrder: 0,
        maxLength: 120,
      },
      {
        key: "employmentType",
        type: "SELECT",
        label: { en: "Employment type", np: "रोजगारीको प्रकार" },
        required: true,
        step: 1,
        sortOrder: 1,
        options: [
          { value: "full_time", label: { en: "Full-time", np: "पूर्णकालीन" } },
          { value: "part_time", label: { en: "Part-time", np: "आंशिक कालीन" } },
          { value: "contract", label: { en: "Fixed-term contract", np: "निश्चित अवधि सम्झौता" } },
          { value: "probation", label: { en: "Probationary", np: "परिवीक्षा" } },
        ],
      },
      {
        key: "probationPeriodMonths",
        type: "NUMBER",
        label: { en: "Probation period (months)", np: "परिवीक्षा अवधि (महिना)" },
        required: true,
        step: 1,
        sortOrder: 2,
        min: 1,
        max: 12,
        visibleWhen: { field: "employmentType", equals: "probation" },
      },
      {
        key: "startDate",
        type: "DATE_AD",
        label: { en: "Start date", np: "सुरु मिति" },
        required: true,
        step: 1,
        sortOrder: 3,
      },
      {
        key: "monthlySalary",
        type: "CURRENCY",
        label: { en: "Monthly salary", np: "मासिक तलब" },
        required: true,
        step: 1,
        sortOrder: 4,
        currency: "NPR",
        min: 0,
      },
      {
        key: "workLocation",
        type: "TEXT",
        label: { en: "Work location", np: "कार्यस्थल" },
        required: false,
        step: 1,
        sortOrder: 5,
      },
      {
        key: "includeConfidentiality",
        type: "CLAUSE_TOGGLE",
        clauseKey: "confidentiality",
        defaultOn: true,
        label: { en: "Include confidentiality clause", np: "गोपनीयता धारा समावेश गर्ने" },
        required: false,
        step: 2,
        sortOrder: 0,
      },
      {
        key: "includeNonCompete",
        type: "CLAUSE_TOGGLE",
        clauseKey: "non_compete",
        defaultOn: false,
        label: { en: "Include non-compete clause", np: "प्रतिस्पर्धा निषेध धारा समावेश गर्ने" },
        required: false,
        step: 2,
        sortOrder: 1,
      },
      {
        key: "customClause",
        type: "FREE_TEXT_CLAUSE",
        label: { en: "Describe any additional clause (optional)", np: "थप धारा वर्णन गर्नुहोस् (वैकल्पिक)" },
        required: false,
        step: 2,
        sortOrder: 2,
        maxLength: 1500,
      },
    ],
    clauses: [
      {
        key: "position_terms",
        titleEn: "Position & Reporting",
        titleNp: "पद र रिपोर्टिङ",
        bodyEn: "Employee accepts the position of {{jobTitle}}, reporting as directed by Employer.",
        bodyNp: "कर्मचारीले {{jobTitle}} पदमा नियुक्ति स्वीकार गर्दछ र रोजगारदाताले तोकेबमोजिम रिपोर्ट गर्नेछ।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 0,
      },
      {
        key: "compensation",
        titleEn: "Compensation",
        titleNp: "पारिश्रमिक",
        bodyEn: "Employee shall be paid a monthly salary of NPR {{monthlySalary}}, subject to applicable statutory deductions.",
        bodyNp: "कर्मचारीलाई मासिक रु. {{monthlySalary}} पारिश्रमिक भुक्तानी हुनेछ, लागू कानुनी कट्टीको अधीनमा रही।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 1,
      },
      {
        key: "confidentiality",
        titleEn: "Confidentiality",
        titleNp: "गोपनीयता",
        bodyEn: "Employee shall keep confidential all proprietary and business information of Employer, both during and after employment.",
        bodyNp: "कर्मचारीले रोजगारीको अवधिभर र पश्चात पनि रोजगारदाताको गोप्य तथा व्यावसायिक जानकारी गोप्य राख्नेछ।",
        isDefault: true,
        isToggleable: true,
        sortOrder: 2,
        riskFlagIfMissing:
          "No confidentiality clause selected — sensitive company information may not be contractually protected.",
      },
      {
        key: "non_compete",
        titleEn: "Non-Compete",
        titleNp: "प्रतिस्पर्धा निषेध",
        bodyEn: "For a reasonable period after termination, Employee shall not engage in directly competing business within Nepal, to the extent enforceable under applicable law.",
        bodyNp: "रोजगारी अन्त्य भएपछि उचित अवधिसम्म, कर्मचारीले लागू कानुन बमोजिम प्रवर्तनयोग्य हदसम्म नेपालभित्र प्रत्यक्ष प्रतिस्पर्धी व्यवसायमा संलग्न हुने छैन।",
        isDefault: false,
        isToggleable: true,
        sortOrder: 3,
      },
      {
        key: "termination_at_will",
        titleEn: "Termination",
        titleNp: "अवकाश",
        bodyEn: "Either party may terminate this employment by providing written notice as required under the Labour Act, 2074 (2017) and Employer's policies.",
        bodyNp: "श्रम ऐन, २०७४ र रोजगारदाताको नीति बमोजिम आवश्यक लिखित सूचना दिई कुनै पनि पक्षले यो रोजगारी अन्त्य गर्न सक्नेछ।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 4,
      },
      {
        key: "governing_law",
        titleEn: "Governing Law & Jurisdiction",
        titleNp: "लागू कानुन र क्षेत्राधिकार",
        bodyEn: "This offer is governed by the laws of Nepal, and disputes shall be subject to the jurisdiction of the competent courts of Nepal.",
        bodyNp: "यो प्रस्ताव नेपालको कानुनद्वारा शासित हुनेछ, र विवादहरू नेपालको सक्षम अदालतको क्षेत्राधिकार अन्तर्गत रहनेछन्।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 5,
        riskFlagIfMissing: "No governing law / jurisdiction clause — disputes may lack a clear venue.",
      },
    ],
  },
  {
    slug: "employment-termination-letter",
    titleEn: "Termination Letter",
    titleNp: "अवकाश पत्र",
    descriptionEn: "A formal notice ending an employee's employment, stating reason and effective date.",
    descriptionNp: "कारण र प्रभावकारी मितिसहित कर्मचारीको रोजगारी अन्त्य गर्ने औपचारिक सूचना।",
    requiresLawyerReview: true,
    isGovernmentFormat: false,
    systemPromptEn:
      "Draft a formal Employment Termination Letter under Nepali labour practice. Use only the " +
      "facts supplied (employee name, position, termination reason category, effective date, " +
      "final settlement terms). Do not assert wrongdoing beyond what the user states. Include: " +
      "reference to employment start date, stated reason category, effective termination date, " +
      "final dues/settlement clause, return-of-property clause if selected, and the standard " +
      "draft disclaimer.",
    systemPromptNp:
      "नेपाली श्रम अभ्यास अनुसार औपचारिक अवकाश पत्र मस्यौदा गर्नुहोस्। प्रयोगकर्ताले दिएका तथ्य " +
      "(कर्मचारीको नाम, पद, कारण, प्रभावकारी मिति, अन्तिम भुक्तानी) मात्र प्रयोग गर्नुहोस्। " +
      "अन्त्यमा मानक ड्राफ्ट अस्वीकरण राख्नुहोस्।",
    fields: [
      {
        key: "employer",
        type: "PARTY_BLOCK",
        partyRole: "employer",
        includeCompanyRegistration: true,
        includeCitizenshipNumber: false,
        label: { en: "Employer", np: "रोजगारदाता" },
        required: true,
        step: 0,
        sortOrder: 0,
      },
      {
        key: "employee",
        type: "PARTY_BLOCK",
        partyRole: "employee",
        includeCitizenshipNumber: true,
        includeCompanyRegistration: false,
        label: { en: "Employee", np: "कर्मचारी" },
        required: true,
        step: 0,
        sortOrder: 1,
      },
      {
        key: "reasonCategory",
        type: "SELECT",
        label: { en: "Reason for termination", np: "अवकाशको कारण" },
        required: true,
        step: 1,
        sortOrder: 0,
        options: [
          { value: "redundancy", label: { en: "Redundancy / restructuring", np: "पद खारेजी / पुनर्संरचना" } },
          { value: "performance", label: { en: "Performance", np: "कार्यसम्पादन" } },
          { value: "misconduct", label: { en: "Misconduct", np: "आचरण" } },
          { value: "mutual", label: { en: "Mutual agreement", np: "आपसी सहमति" } },
        ],
      },
      {
        key: "effectiveDate",
        type: "DATE_AD",
        label: { en: "Effective date", np: "प्रभावकारी मिति" },
        required: true,
        step: 1,
        sortOrder: 1,
      },
      {
        key: "finalSettlementAmount",
        type: "CURRENCY",
        label: { en: "Final settlement amount", np: "अन्तिम भुक्तानी रकम" },
        required: false,
        step: 1,
        sortOrder: 2,
        currency: "NPR",
      },
      {
        key: "customClause",
        type: "FREE_TEXT_CLAUSE",
        label: { en: "Describe any additional clause (optional)", np: "थप धारा वर्णन गर्नुहोस् (वैकल्पिक)" },
        required: false,
        step: 2,
        sortOrder: 0,
        maxLength: 1500,
      },
    ],
    clauses: [
      {
        key: "termination_statement",
        titleEn: "Termination Statement",
        titleNp: "अवकाश कथन",
        bodyEn: "Employer hereby terminates Employee's employment effective {{effectiveDate}}.",
        bodyNp: "रोजगारदाताले कर्मचारीको रोजगारी {{effectiveDate}} देखि अन्त्य गर्दछ।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 0,
      },
      {
        key: "final_settlement",
        titleEn: "Final Settlement",
        titleNp: "अन्तिम भुक्तानी",
        bodyEn: "All final dues, including accrued but unpaid salary and benefits, shall be settled per Employer's policy and applicable law.",
        bodyNp: "बाँकी तलब र सुविधाहरू सहित सम्पूर्ण अन्तिम भुक्तानी रोजगारदाताको नीति र लागू कानुन बमोजिम फर्स्योट गरिनेछ।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 1,
        riskFlagIfMissing: "No final settlement clause — the settlement basis is unclear.",
      },
      {
        key: "return_of_property",
        titleEn: "Return of Company Property",
        titleNp: "कम्पनीको सम्पत्ति फिर्ता",
        bodyEn: "Employee shall return all company property, documents, and access credentials by the effective date.",
        bodyNp: "कर्मचारीले प्रभावकारी मितिसम्ममा कम्पनीको सम्पूर्ण सम्पत्ति, कागजात र पहुँच फिर्ता गर्नुपर्नेछ।",
        isDefault: true,
        isToggleable: true,
        sortOrder: 2,
      },
    ],
  },
] as const;
