export const rentalTemplates = [
  {
    slug: "residential-rental-agreement",
    titleEn: "Residential Rental/Lease Agreement",
    titleNp: "घर भाडा सम्झौता",
    descriptionEn: "A lease agreement between a landlord and tenant for a residential property.",
    descriptionNp: "घरधनी र भाडावालबीचको आवासीय घर भाडा सम्झौता।",
    requiresLawyerReview: true,
    isGovernmentFormat: false,
    systemPromptEn:
      "Draft a Residential Rental/Lease Agreement (घर भाडा सम्झौता) reflecting standard Nepali " +
      "rental practice. Use only the landlord/tenant details, property address, rent amount, " +
      "deposit, and term provided. Structure: recitals identifying both parties and the " +
      "property, rent and payment schedule, security deposit terms (if included), duration and " +
      "renewal, maintenance responsibilities, utilities, termination/notice period, dispute " +
      "resolution, witness/signature block with space for a notarial stamp. End with the " +
      "standard draft disclaimer.",
    systemPromptNp:
      "नेपाली भाडा अभ्यास अनुसार घर भाडा सम्झौता मस्यौदा गर्नुहोस्। प्रयोगकर्ताले दिएका घरधनी/भाडावालको " +
      "विवरण, सम्पत्तिको ठेगाना, भाडा रकम, धरौटी र अवधि मात्र प्रयोग गर्नुहोस्। साक्षी र हस्ताक्षर " +
      "खण्ड समावेश गर्नुहोस्। अन्त्यमा मानक ड्राफ्ट अस्वीकरण राख्नुहोस्।",
    fields: [
      {
        key: "landlord",
        type: "PARTY_BLOCK",
        partyRole: "landlord",
        includeCitizenshipNumber: true,
        includeCompanyRegistration: false,
        label: { en: "Landlord", np: "घरधनी" },
        required: true,
        step: 0,
        sortOrder: 0,
      },
      {
        key: "tenant",
        type: "PARTY_BLOCK",
        partyRole: "tenant",
        includeCitizenshipNumber: true,
        includeCompanyRegistration: false,
        label: { en: "Tenant", np: "भाडावाल" },
        required: true,
        step: 0,
        sortOrder: 1,
      },
      {
        key: "propertyAddress",
        type: "TEXTAREA",
        label: { en: "Property address", np: "सम्पत्तिको ठेगाना" },
        required: true,
        step: 1,
        sortOrder: 0,
        maxLength: 500,
      },
      {
        key: "monthlyRent",
        type: "CURRENCY",
        label: { en: "Monthly rent", np: "मासिक भाडा" },
        required: true,
        step: 1,
        sortOrder: 1,
        currency: "NPR",
        min: 0,
      },
      {
        key: "leaseStartDateBs",
        type: "DATE_BS",
        label: { en: "Lease start date (B.S.)", np: "सम्झौता सुरु मिति (वि.सं.)" },
        required: true,
        step: 1,
        sortOrder: 2,
      },
      {
        key: "leaseTermMonths",
        type: "NUMBER",
        label: { en: "Lease term (months)", np: "सम्झौता अवधि (महिना)" },
        required: true,
        step: 1,
        sortOrder: 3,
        min: 1,
        max: 120,
      },
      {
        key: "includeSecurityDeposit",
        type: "CLAUSE_TOGGLE",
        clauseKey: "security_deposit",
        defaultOn: true,
        label: { en: "Include security deposit clause", np: "धरौटी धारा समावेश गर्ने" },
        required: false,
        step: 1,
        sortOrder: 4,
      },
      {
        key: "securityDepositAmount",
        type: "CURRENCY",
        label: { en: "Security deposit amount", np: "धरौटी रकम" },
        required: true,
        step: 1,
        sortOrder: 5,
        currency: "NPR",
        min: 0,
        visibleWhen: { field: "includeSecurityDeposit", equals: true },
      },
      {
        key: "customClause",
        type: "FREE_TEXT_CLAUSE",
        label: { en: "Describe any additional clause (optional)", np: "थप धारा वर्णन गर्नुहोस् (वैकल्पिक)" },
        required: false,
        step: 2,
        sortOrder: 0,
        maxLength: 1500,
      },
    ],
    clauses: [
      {
        key: "premises_description",
        titleEn: "Premises",
        titleNp: "घर/कोठाको विवरण",
        bodyEn: "Landlord agrees to lease the premises located at {{propertyAddress}} to Tenant.",
        bodyNp: "घरधनीले {{propertyAddress}} मा रहेको घर/कोठा भाडावाललाई भाडामा दिन सहमत हुनुहुन्छ।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 0,
      },
      {
        key: "rent_payment",
        titleEn: "Rent & Payment",
        titleNp: "भाडा भुक्तानी",
        bodyEn: "Tenant shall pay Landlord a monthly rent of NPR {{monthlyRent}}, payable in advance by the 5th of each month.",
        bodyNp: "भाडावालले घरधनीलाई प्रत्येक महिनाको ५ गते भित्र रु. {{monthlyRent}} अग्रिम भाडा भुक्तानी गर्नेछ।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 1,
      },
      {
        key: "security_deposit",
        titleEn: "Security Deposit",
        titleNp: "धरौटी",
        bodyEn: "Tenant shall pay a refundable security deposit of NPR {{securityDepositAmount}}, refundable upon vacating the premises subject to deductions for damages.",
        bodyNp: "भाडावालले रु. {{securityDepositAmount}} फिर्ता हुने धरौटी बुझाउनेछ, जुन घर खाली गर्दा क्षतिको कट्टी गरी फिर्ता हुनेछ।",
        isDefault: true,
        isToggleable: true,
        sortOrder: 2,
        riskFlagIfMissing: "No security deposit clause selected — recovery of damages may be harder to enforce.",
      },
      {
        key: "maintenance",
        titleEn: "Maintenance & Utilities",
        titleNp: "मर्मत तथा उपयोगिता",
        bodyEn: "Tenant shall bear utility charges (electricity, water, internet); Landlord is responsible for structural repairs.",
        bodyNp: "भाडावालले विद्युत, पानी, इन्टरनेट जस्ता उपयोगिता शुल्क बेहोर्नेछ; संरचनात्मक मर्मतको जिम्मा घरधनीको हुनेछ।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 3,
      },
      {
        key: "termination_notice",
        titleEn: "Termination & Notice",
        titleNp: "अन्त्य तथा सूचना",
        bodyEn: "Either party may terminate this agreement by providing at least 30 days' written notice.",
        bodyNp: "कुनै पनि पक्षले कम्तीमा ३० दिनको लिखित सूचना दिई यो सम्झौता अन्त्य गर्न सक्नेछ।",
        isDefault: true,
        isToggleable: false,
        sortOrder: 4,
        riskFlagIfMissing: "No termination/notice period clause — either party's exit terms are unclear.",
      },
      {
        key: "dispute_resolution",
        titleEn: "Dispute Resolution",
        titleNp: "विवाद समाधान",
        bodyEn: "Disputes arising from this agreement shall first be resolved through mutual negotiation, failing which the competent courts of Nepal shall have jurisdiction.",
        bodyNp: "यस सम्झौताबाट उत्पन्न विवाद पहिले आपसी वार्ताबाट समाधान गरिनेछ, असफल भएमा नेपालको सक्षम अदालतको क्षेत्राधिकार लाग्नेछ।",
        isDefault: true,
        isToggleable: true,
        sortOrder: 5,
        riskFlagIfMissing: "No dispute resolution clause selected.",
      },
    ],
  },
] as const;
